-- ═══════════════════════════════════════════════════════════
-- Hero Ascension — Supabase Database Schema (Production)
-- ═══════════════════════════════════════════════════════════

-- Enable UUID generation
create extension if not exists "pgcrypto";

-- ── 1. users ──────────────────────────────────────────────────────────
create table if not exists users (
  id            uuid primary key default gen_random_uuid(),
  name          text not null,
  email         text not null unique,
  password_hash text not null,
  created_at    timestamptz not null default now()
);

-- ── 2. profiles ───────────────────────────────────────────────────────
-- Stores user-specific global state
create table if not exists profiles (
  user_id           uuid primary key references users(id) on delete cascade,
  selected_hero_id  text,
  xp                int not null default 0,
  onboarded         boolean not null default false,
  updated_at        timestamptz not null default now()
);

-- ── 3. habits ─────────────────────────────────────────────────────────
create table if not exists habits (
  id            text primary key, -- Use the h_uuid generated by frontend or backend
  user_id       uuid not null references users(id) on delete cascade,
  title         text not null,
  category      text not null default 'fitness',
  monthly_goal  int not null default 25,
  repeat_days   text[] default '{}', -- e.g. {'mon', 'wed', 'fri'}
  priority      text not null default 'medium',
  xp_reward     int not null default 20,
  created_at    timestamptz not null default now()
);

-- ── 4. habit_logs ─────────────────────────────────────────────────────
create table if not exists habit_logs (
  id            uuid primary key default gen_random_uuid(),
  user_id       uuid not null references users(id) on delete cascade,
  habit_id      text not null references habits(id) on delete cascade,
  log_date      date not null,
  completed     boolean not null default true,
  unique(user_id, habit_id, log_date)
);

-- ── 5. calendar_todos ─────────────────────────────────────────────────
create table if not exists calendar_todos (
  id            text primary key, -- ct_timestamp
  user_id       uuid not null references users(id) on delete cascade,
  todo_date     date not null,
  title         text not null,
  completed     boolean not null default false,
  created_at    timestamptz not null default now()
);

-- ── 6. Goals (Optional but kept from original) ────────────────────────
create table if not exists goals (
  id             uuid primary key default gen_random_uuid(),
  user_id        uuid not null references users(id) on delete cascade,
  title          text not null,
  target_value   int  not null default 100,
  current_value  int  not null default 0,
  deadline       date,
  status         text not null default 'active',
  created_at     timestamptz not null default now()
);

-- ── Indexes ──────────────────────────────────────────────────────────
create index if not exists idx_habits_user     on habits(user_id);
create index if not exists idx_logs_user_date  on habit_logs(user_id, log_date);
create index if not exists idx_todos_user_date on calendar_todos(user_id, todo_date);
